# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_login.ipynb.

# %% auto 0
__all__ = ['Login']

# %% ../nbs/01_login.ipynb 3
import ipywidgets as widgets
from ipywidgets import VBox, HTML, HBox, Label, Tab, Output, Button, Text
from IPython.display import display, clear_output
import ipyvuetify as v


# %% ../nbs/01_login.ipynb 4
class Login(VBox):
    
    def __init__(self):
        super().__init__()
        
        # Username input
        self.username_input = v.TextField(label='Username:', placeholder='Enter username')
        
        # Password input   
        self.key_input = v.TextField(label='API Key:', placeholder='Enter API key')
        
        # Login button
        self.login_button = Button(description='Login')

        #Header
        self.header = v.Container(children=[
            v.Html(
                tag='h1',
                attributes={'title': 'a title'},
                children=['Log In']
            )
        ])

        
        # Arrange widgets vertically
        self.children = [
            self.header,  # Heading
            self.username_input,       # Username label and input box
            self.key_input,       # Password label and input box
            HBox([self.login_button], layout={'justify_content': 'flex-end'}),  # Login button aligned to the right
        ]
